### ISSUE TITLE
Create Python integration tests

### ISSUE THREAD

**Issue by afoerster** [phdata/sdc-api-tool#1]
I'm not huge on a lot of unit tests for an application like this because it doesn't have a lot of branching and most of the work it does is with an external tool. Mocking is mostly a waste when dealing with an external api so Docker seems the good choice for most testing. The current docker 'test' is just a temporary hack, tests written in python that do real assertion and container cleanup are needed.

**Comment by bpmcd** [comment]
Closed by [PR12](https://github.com/phdata/sdc-api-tool/pull/12)
